project:
    # publishing to github pages
    # ref: https://quarto.org/docs/publishing/github-pages.html#render-to-docs
    type: website
    output-dir: docs
    resources:
        - CNAME

website:
    title: "Guillaume Dehaene"
    site-url: www.guillaumedehaene.com
    page-footer: "This website was created with [Quarto](https://quarto.org/)." 
    navbar:
        left:
            - blog.qmd
        right:
            - publications.qmd
            -   href: about.html
                # file: about.qmd
                text: About me

format:
    html:
        # theme:
        #     light: cosmo
        #     dark: cosmo
        # theme:
        #     light: flatly
        #     dark: darkly
        theme: cosmo
        mermaid:
            theme: neutral
        mainfont: "EB Garamond, Georgia, serif"
        toc: true
        include-in-header:
            text: |
                <style>
                @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap')
                </style>
                <script>
                MathJax = {
                    tex: {
                        tags: 'ams'  // should be 'ams', 'none', or 'all'
                    }
                };
                </script>
