project:
  type: website

website:
  title: "Guillaume Dehaene"
  page-footer: "This website was created with [Quarto](https://quarto.org/)." 
  navbar:
    left:
        - blog.qmd
    right:
        - publications.qmd
        -   file: about.qmd
            text: About me

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    include-in-header:
      text: |
        <script>
        MathJax = {
            tex: {
                tags: 'ams'  // should be 'ams', 'none', or 'all'
            }
        };
        </script>
