project:
    # publishing to github pages
    # ref: https://quarto.org/docs/publishing/github-pages.html#render-to-docs
    type: website
    output-dir: docs
    resources:
        - CNAME

website:
    title: "Guillaume Dehaene"
    site-url: www.guillaumedehaene.com
    page-footer: "This website was created with [Quarto](https://quarto.org/)." 
    page-navigation: true
    back-to-top-navigation: true
    # page-footer:
        #     center: 
        #     - text: "About"
        #         href: about.qmd
        #     - text: "License"
        #         href: license.qmd
        #     - text: "Trademark"
        #         href: trademark.qmd
    navbar:
        left:
            - blog.qmd
        right:
            - publications.qmd
            -   href: about.html
                # file: about.qmd
                text: About me

format:
    html:
        theme:
            - cosmo
            - style.scss
        mainfont: "EB Garamond, Georgia, serif"
        monofont: Fira Code, consolas, courier, monospace
        highlight-style: github

        html-math-method:
            method: mathjax
            url: "https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-mml-chtml.js"
        include-in-header:
            text: |
                <style>
                @import url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap')
                @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap')
                </style>
                <script>
                MathJax = {
                    tex: {
                        tags: 'ams'  // should be 'ams', 'none', or 'all'
                    },
                    output: {
                        font: 'mathjax-fira'
                    }
                };
                </script>
        
        # Provides a navigation menu for the content on the page
        toc: true
        toc-location: right-body
        
        # number sections like a latex article
        number-sections: true
        number-depth: 3
        shift-heading-level-by: 1

        anchor-sections: true

        # provide code copy button
        code-copy: true

        # show qmd source
        code-tools: true

        # freeze computations
        freeze: auto

        link-external-icon: true
        link-external-newwindow: true

        lang: en

        # remove html comments from source
        strip-comments: true

